### ISSUE TITLE
Commodore 64 lack of content

### ISSUE THREAD

**Issue by 3XistencE** [libretro-thumbnails/Commodore_-_64#2]
The Branch is pretty empty of content.

Actually i have some free time to convert/resize/upload the various boxarts.
The guideline is wide 512px, png format indexed?

Give some love to Commodore 64

**Comment by RobLoach** [comment]
Correct! Would love to see these grow.

- 512px wide (height doesn't matter)
- PNG

**Comment by JWParenteau** [comment]
Something must have happened during the migration to GitHub because there is far fewer box art than there is in this location:
[https://thumbnails.libretro.com/Commodore%20-%2064/Named_Boxarts/](https://thumbnails.libretro.com/Commodore%20-%2064/Named_Boxarts/).

**Comment by RobLoach** [comment]
It's over at https://github.com/libretro-thumbnails/Commodore_-_64/tree/master/Named_Boxarts
